package com.devstdvad.devicedna.domain.model

data class DeviceInfo(
    val name: String,
    val model: String,
    val manufacturer: String,
    val brand: String,
    val board: String,
    val hardware: String,
    val codename: String,
    val buildFingerprint: String,
    val androidId: String,
    val supportedAbis: List<String>,
    val isRooted: Boolean,
    val bootloader: String,
    val socName: String = "",
    val serialNumber: String = "",
    val isEmulator: Boolean = false,
    val isDeveloperOptionsEnabled: Boolean = false,
    val isAdbEnabled: Boolean = false,
    val buildTags: String = "",
    val buildUser: String = "",
    val buildHost: String = "",
    val buildTimeMillis: Long = 0L,
    val isTestKeysBuild: Boolean = false,
    val isDebuggableBuild: Boolean = false,
    val verifiedBootState: String = "",
    val bootVerifiedState: String = "",
    val vbMetaDeviceState: String = "",
    val flashLocked: String = "",
    val verityMode: String = "",
    val warrantyBit: String = "",
    val firstApiLevel: Int? = null,
    val suspiciousRootPaths: List<String> = emptyList(),
)
