#!/usr/bin/env bash
# Fan out secrets.properties into the generated config files each toolchain expects.
#
#   ./scripts/sync-config.sh
#
# Generates (all gitignored):
#   backend/.dev.vars        — env for local `wrangler dev`
#   backend/wrangler.toml    — from wrangler.toml.template
#   ios/settings.local.yml   — build settings consumed by ios/project.yml
#   .firebaserc              — firebase CLI project selection
#
# Gradle reads secrets.properties directly, so Android needs no generated file.
# Worker production secrets are uploaded separately by backend/setup-cloudflare.sh.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"
# shellcheck source=lib/config.sh
source "$REPO_ROOT/scripts/lib/config.sh"

require_secrets_file

# Needed to render the iOS project and .firebaserc — no client build without them.
require_values \
    androidApplicationId \
    iosBundleId iosWidgetBundleId iosAppGroupId iosBackgroundTaskId iosDeepLinkScheme \
    iosGoogleReversedClientId iosStoreKitPremiumProductId \
    firebaseProjectId syncBaseUrl premiumSubProductId cfgPubKey \
    cloudflareWorkerName

# Backend-only. A client-side sync stays useful without them, so warn instead of failing;
# setup-cloudflare.sh prompts for whatever is still missing at deploy time.
for name in firebaseWebApiKey databaseUrl; do
    [ -z "$(cfg "$name")" ] && echo "warning: $name is empty — backend/.dev.vars will omit it" >&2
done
true

# Emit a KEY="value" line, escaping backslashes and double quotes for .dev.vars.
dev_var() {
    local name="$1" value="$2"
    [ -z "$value" ] && return 0
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '%s="%s"\n' "$name" "$value"
}

# ── backend/.dev.vars ────────────────────────────────────────────────────────
# The file is regenerated wholesale, so a value that only ever lived there (and never
# made it into secrets.properties) would be silently destroyed. Back it up and name
# the keys that are about to disappear.
if [ -f backend/.dev.vars ]; then
    cp backend/.dev.vars backend/.dev.vars.bak
    while IFS='=' read -r key _; do
        case "$key" in ''|'#'*) continue ;; esac
        prop="$(python3 -c '
import re, sys
key = sys.argv[1]
print(re.sub(r"_([a-z])", lambda m: m.group(1).upper(), key.lower()))' "$key")"
        [ -z "$(cfg "$prop")" ] && echo "warning: $key was set in .dev.vars but $prop is empty in secrets.properties" >&2
    done < backend/.dev.vars
fi

echo "==> backend/.dev.vars"
{
    echo "# Generated by scripts/sync-config.sh from secrets.properties. Do not edit."
    echo ""
    dev_var FIREBASE_PROJECT_ID "$(cfg firebaseProjectId)"
    dev_var FIREBASE_WEB_API_KEY "$(cfg firebaseWebApiKey)"
    dev_var DATABASE_URL "$(cfg databaseUrl)"
    dev_var GOOGLE_PLAY_PACKAGE_NAME "$(cfg googlePlayPackageName androidApplicationId)"
    dev_var GOOGLE_PLAY_PREMIUM_PRODUCT_ID "$(cfg googlePlayPremiumProductId premiumSubProductId)"
    dev_var INTERNAL_API_KEY "$(cfg internalApiKey)"
    dev_var GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL "$(cfg googlePlayServiceAccountEmail)"
    dev_var GOOGLE_PLAY_PRIVATE_KEY "$(cfg googlePlayPrivateKey)"
    dev_var PLAY_RTDN_VERIFICATION_TOKEN "$(cfg playRtdnVerificationToken)"
    dev_var DEV_SUBSCRIPTIONS_ENABLED "$(cfg devSubscriptionsEnabled)"
} > backend/.dev.vars

# ── ios/settings.local.yml ───────────────────────────────────────────────────
# XcodeGen merges this via `include:` in project.yml. Values are JSON-encoded
# because JSON is a subset of YAML, so base64 padding and URLs survive intact.
echo "==> ios/settings.local.yml"
export SC_IOS_BUNDLE_ID="$(cfg iosBundleId)"
export SC_IOS_WIDGET_BUNDLE_ID="$(cfg iosWidgetBundleId)"
export SC_IOS_APP_GROUP_ID="$(cfg iosAppGroupId)"
export SC_IOS_BACKGROUND_TASK_ID="$(cfg iosBackgroundTaskId)"
export SC_IOS_DEEP_LINK_SCHEME="$(cfg iosDeepLinkScheme)"
export SC_IOS_REVERSED_CLIENT_ID="$(cfg iosGoogleReversedClientId)"
export SC_IOS_STOREKIT_PRODUCT_ID="$(cfg iosStoreKitPremiumProductId)"
export SC_IOS_ADMOB_APP_ID="$(cfg iosAdMobAppId)"
export SC_IOS_ADMOB_BANNER="$(cfg iosAdMobBannerAdUnitId)"
export SC_IOS_ADMOB_INTERSTITIAL="$(cfg iosAdMobInterstitialAdUnitId)"
export SC_SYNC_BASE_URL="$(cfg syncBaseUrl)"
export SC_CFG_PUBKEY="$(cfg cfgPubKey)"
export SC_CFG_DOC_PATH="$(cfg cfgDocPath)"

python3 - <<'PY'
import json, os

def env(name):
    return os.environ.get(name, "")

settings = {
    "IOS_APP_BUNDLE_ID": env("SC_IOS_BUNDLE_ID"),
    "IOS_WIDGET_BUNDLE_ID": env("SC_IOS_WIDGET_BUNDLE_ID"),
    "IOS_APP_GROUP_ID": env("SC_IOS_APP_GROUP_ID"),
    "IOS_BACKGROUND_TASK_ID": env("SC_IOS_BACKGROUND_TASK_ID"),
    "IOS_DEEP_LINK_SCHEME": env("SC_IOS_DEEP_LINK_SCHEME"),
    "GOOGLE_REVERSED_CLIENT_ID": env("SC_IOS_REVERSED_CLIENT_ID"),
    "IOS_STOREKIT_PREMIUM_PRODUCT_ID": env("SC_IOS_STOREKIT_PRODUCT_ID"),
    # Google's official test ids: always serve test ads, never earn revenue.
    "IOS_ADMOB_APP_ID": env("SC_IOS_ADMOB_APP_ID") or "ca-app-pub-3940256099942544~1458002511",
    "IOS_ADMOB_BANNER_AD_UNIT_ID": env("SC_IOS_ADMOB_BANNER") or "ca-app-pub-3940256099942544/2934735716",
    "IOS_ADMOB_INTERSTITIAL_AD_UNIT_ID": env("SC_IOS_ADMOB_INTERSTITIAL") or "ca-app-pub-3940256099942544/4411468910",
    "SYNC_BASE_URL": env("SC_SYNC_BASE_URL").rstrip("/"),
    "CFG_PUBKEY": env("SC_CFG_PUBKEY"),
    "CFG_DOC_PATH": env("SC_CFG_DOC_PATH") or "cfg/state",
}

lines = [
    "# Generated by scripts/sync-config.sh from secrets.properties. Do not edit.",
    "# Included by project.yml; XcodeGen merges these into `settings.base`.",
    "",
    "settings:",
    "  base:",
]
lines += [f"    {k}: {json.dumps(v)}" for k, v in settings.items()]
with open("ios/settings.local.yml", "w") as f:
    f.write("\n".join(lines) + "\n")
PY

# ── backend/wrangler.toml ────────────────────────────────────────────────────
# An empty cloudflareKvId means the namespace does not exist yet; emit the sentinel
# setup-cloudflare.sh looks for, so it creates the namespace and fills the id in.
echo "==> backend/wrangler.toml"
export SC_WORKER_NAME="$(cfg cloudflareWorkerName)"
export SC_KV_ID="$(cfg cloudflareKvId)"
python3 - <<'PY'
import os
name = os.environ["SC_WORKER_NAME"]
kv_id = os.environ["SC_KV_ID"] or "REPLACE_AFTER_wrangler_kv_namespace_create"
with open("backend/wrangler.toml.template") as f:
    toml = f.read()
toml = toml.replace("{{CLOUDFLARE_WORKER_NAME}}", name).replace("{{CLOUDFLARE_KV_ID}}", kv_id)
toml = toml.replace(
    "# TEMPLATE — edit this file, never backend/wrangler.toml.",
    "# GENERATED by scripts/sync-config.sh from wrangler.toml.template. Do not edit.",
)
with open("backend/wrangler.toml", "w") as f:
    f.write(toml)
PY

# ── .firebaserc ──────────────────────────────────────────────────────────────
echo "==> .firebaserc"
export SC_FIREBASE_PROJECT_ID="$(cfg firebaseProjectId)"
python3 - <<'PY'
import json, os
project = os.environ["SC_FIREBASE_PROJECT_ID"]
with open(".firebaserc", "w") as f:
    json.dump({"projects": {"default": project}}, f, indent=2)
    f.write("\n")
PY

echo ""
echo "Done. Next:"
echo "  Android : ./gradlew :android:assembleDebug        (reads secrets.properties directly)"
echo "  Backend : cd backend && npx wrangler dev          (reads .dev.vars)"
echo "            cd backend && ./setup-cloudflare.sh     (uploads production secrets)"
echo "  iOS     : cd ios && xcodegen generate && pod install"
